import Head from "next/head";
import LandingPage from "./landing_page";
import "aos/dist/aos.css";
import { useEffect, useState } from "react";
import Login from "./login";
import jwt from "jsonwebtoken";

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  const initializeAOS = () => {
    import("aos").then((AOS) => {
      AOS.default.init();
    });
  };

  useEffect(() => {
    initializeAOS();

    if (typeof window !== "undefined") {
      const userData: any = localStorage.getItem("userData");
      const userParse: any = userData && JSON.parse(userData);

      if (userParse && userParse) {
        const decodedToken: any = jwt.decode(userParse.token, {
          complete: true,
        });
        const expire = decodedToken?.payload;
        if (expire && expire.exp) {
          const currentTime = Math.floor(Date.now() / 1000);
          if (currentTime > expire.exp) {
            setIsLoggedIn(false);
          } else {
            setIsLoggedIn(true);
          }
        }
      } else {
        setIsLoggedIn(true);
      }
    }
  }, []);

  return (
    <>
      <Head>
        <title>Bolo Ticketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
          type="text/javascript"
        ></script>
      </Head>
      {isLoggedIn ? <LandingPage /> : <Login />}
    </>
  );
}
